### ISSUE TITLE
Request: allow deferred specification of registration parameters

### ISSUE THREAD

**Issue by iain-anderson** [edgexfoundry/go-mod-registry#15]
(For Fuji)
The information needed for service registration (host, port, checking interval) is likely to be contained in the configuration for that service. It would be useful to be able to set up a registry client without these settings, then use the client to get the config, then register the service (only at that last stage specifying the relevant parameters)

**Comment by lenny-intel** [comment]
@iain-anderson, good catch. This is a **bug**. 

If one was to change the port for a service from the Registry, aka Consul, and then restart the service, that service will improperly register with the old port from the local configuration. The service will be running on the new port set in the Registry. The health checks from the Registry will fail due to using the old port and the other services querying the endpoint for that service will get the incorrect port.

The following needs to happen:

1. The Register() API needs to be changed to be pass the address and port from the configuration.
2. Each service's init code would have to be refactored to call the Register() API after receiving the configuration from the Registry. Currently the call to Register() occurs before...

**Comment by lenny-intel** [comment]
I think this one will get dealt with by the splitting out of Configuration provider per my Registry Refactoring design. Will revisit this after that is complete.

**Comment by lenny-intel** [comment]
This was resolved via the redesign to split out Registry and Configuration providers. No service registration is done after configuration has been fully initialized.
